import "dotenv/config";
import express from "express";
import { authRouter } from "./auth/routes";
import { dashboardRouter } from "./routes/dashboard";
import { financeiroRouter } from "./routes/financeiro";
import { recebimentosRouter } from "./routes/recebimentos";
import { inadimplenciaRouter } from "./routes/inadimplencia";
import { clientesFinanceiroRouter } from "./routes/clientesFinanceiro";
import { fluxoCaixaRouter } from "./routes/fluxoCaixa";
import { historicoFinanceiroRouter } from "./routes/historicoFinanceiro";
import { projetosRouter } from "./routes/projetos";
import { usersRouter } from "./routes/users";
import { scheduleEmpresaSync } from "./sync/empresaSync";
import { scheduleFilialSync } from "./sync/filialSync";
import { scheduleClienteSync } from "./sync/clienteSync";
import { scheduleTipoTituloSync } from "./sync/tipoTituloSync";
import { scheduleTituloReceberSync } from "./sync/tituloReceberSync";
import { scheduleMovimentoTituloReceberSync } from "./sync/movimentoTituloReceberSync";
import { scheduleRepresentanteSync } from "./sync/representanteSync";
import { scheduleCentroCustoSync } from "./sync/centroCustoSync";
import { scheduleMovimentoContaSync } from "./sync/movimentoContaSync";
import { scheduleNaturezaFinanceiraSync } from "./sync/naturezaFinanceiraSync";
import { schedulePortadorSync } from "./sync/portadorSync";
import { scheduleMoedaSync } from "./sync/moedaSync";
import { scheduleContaCorrenteSync } from "./sync/contaCorrenteSync";
import { scheduleTransacaoSync } from "./sync/transacaoSync";
import { schedulePropostaSync } from "./sync/propostaSync";
import { schedulePropostaItemSync } from "./sync/propostaItemSync";
import { scheduleConsultorSync } from "./sync/consultorSync";

const app = express();
app.use(express.json());

app.use("/auth", authRouter);
app.use("/dashboard", dashboardRouter);
app.use("/financeiro", financeiroRouter);
app.use("/financeiro/recebimentos", recebimentosRouter);
app.use("/financeiro/inadimplencia", inadimplenciaRouter);
app.use("/financeiro/clientes", clientesFinanceiroRouter);
app.use("/financeiro/fluxo-caixa", fluxoCaixaRouter);
app.use("/financeiro/historico", historicoFinanceiroRouter);
app.use("/projetos", projetosRouter);
app.use("/users", usersRouter);

const port = process.env.PORT ? Number(process.env.PORT) : 3001;

app.listen(port, () => {
  console.log(`CaxHub backend rodando na porta ${port}`);
  scheduleEmpresaSync();
  scheduleFilialSync();
  scheduleClienteSync();
  scheduleTipoTituloSync();
  scheduleTituloReceberSync();
  scheduleMovimentoTituloReceberSync();
  scheduleRepresentanteSync();
  scheduleCentroCustoSync();
  scheduleMovimentoContaSync();
  scheduleNaturezaFinanceiraSync();
  schedulePortadorSync();
  scheduleMoedaSync();
  scheduleContaCorrenteSync();
  scheduleTransacaoSync();
  schedulePropostaSync();
  schedulePropostaItemSync();
  scheduleConsultorSync();
});
