// Catalogo das tabelas do Senior HCM (Vetorh) que o modulo RH espelha. Cada entrada vira UM job de
// sincronizacao (sync/hcm/definirSyncHcm.ts) e UM model Prisma (schema.prisma, "modulo RH").
// A ORDEM e a de dependencia: cadastros antes dos fatos.
//
// Gerado a partir do dicionario do HCM da Soeltech (rhsenior.dbo.*) em 09/10/2026; PKs vindas de
// r996tbl. LGPD: as colunas aqui sao as unicas que a query traz. CPF, PIS, CTPS, RG, endereco,
// telefone, dados bancarios, Pix e CID/obs de afastamento nunca entram.
//
// `origem` e o nome da coluna no Senior (minusculas) e tambem o nome do campo/coluna local;
// `cast` e o cast do INSERT em lote; `pk` marca a chave primaria (na ordem de r996tbl).
// `campoData` (quando existe) habilita o modo "Alterados" da tela de sincronizacao.

export type CastHcm = "int" | "bigint" | "numeric" | "date" | "text";

export interface ColunaHcm {
  origem: string;
  cast: CastHcm;
  pk?: boolean;
}

export interface TabelaHcm {
  jobName: string;
  displayName: string;
  /** Nome da tabela no Senior, sem prefixo de banco (o prefixo vem de SENIOR_HCM_BANCO). */
  tabela: string;
  /** Nome da tabela local (@@map do model Prisma). */
  tabelaLocal: string;
  campoData: string | null;
  colunas: ColunaHcm[];
}

export const TABELAS_HCM: TabelaHcm[] = [
  {
    jobName: "hcm-empresas-sync",
    displayName: "Empresas (HCM)",
    tabela: "r030emp",
    tabelaLocal: "hcm_empresas",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "nomemp", cast: "text" },
      { origem: "apeemp", cast: "text" },
      { origem: "sigemp", cast: "text" },
    ],
  },
  {
    jobName: "hcm-filiais-sync",
    displayName: "Filiais (HCM)",
    tabela: "r030fil",
    tabelaLocal: "hcm_filiais",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "codfil", cast: "int", pk: true },
      { origem: "nomfil", cast: "text" },
      { origem: "razsoc", cast: "text" },
      { origem: "codest", cast: "text" },
      { origem: "codcid", cast: "int" },
    ],
  },
  {
    jobName: "hcm-locais-sync",
    displayName: "Locais de Trabalho (HCM)",
    tabela: "r016orn",
    tabelaLocal: "hcm_locais",
    campoData: null,
    colunas: [
      { origem: "taborg", cast: "int", pk: true },
      { origem: "numloc", cast: "int", pk: true },
      { origem: "nomloc", cast: "text" },
      { origem: "datcri", cast: "date" },
      { origem: "datext", cast: "date" },
    ],
  },
  {
    jobName: "hcm-cargos-sync",
    displayName: "Cargos (HCM)",
    tabela: "r024car",
    tabelaLocal: "hcm_cargos",
    campoData: null,
    colunas: [
      { origem: "estcar", cast: "int", pk: true },
      { origem: "codcar", cast: "text", pk: true },
      { origem: "titred", cast: "text" },
      { origem: "titcar", cast: "text" },
      { origem: "codcbo", cast: "text" },
      { origem: "datcri", cast: "date" },
      { origem: "datext", cast: "date" },
    ],
  },
  {
    jobName: "hcm-postos-sync",
    displayName: "Postos de Trabalho (HCM)",
    tabela: "r017pos",
    tabelaLocal: "hcm_postos",
    campoData: null,
    colunas: [
      { origem: "estpos", cast: "int", pk: true },
      { origem: "postra", cast: "text", pk: true },
      { origem: "desred", cast: "text" },
      { origem: "despos", cast: "text" },
      { origem: "datcri", cast: "date" },
      { origem: "datext", cast: "date" },
    ],
  },
  {
    jobName: "hcm-centros-custo-sync",
    displayName: "Centros de Custo (HCM)",
    tabela: "r018ccu",
    tabelaLocal: "hcm_centros_custo",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "codccu", cast: "text", pk: true },
      { origem: "nomccu", cast: "text" },
      { origem: "codfil", cast: "int" },
      { origem: "tipcta", cast: "text" },
      { origem: "posccu", cast: "text" },
      { origem: "datcri", cast: "date" },
      { origem: "datext", cast: "date" },
    ],
  },
  {
    jobName: "hcm-situacoes-sync",
    displayName: "Situações do Ponto: cadastro (HCM)",
    tabela: "r010sit",
    tabelaLocal: "hcm_situacoes",
    campoData: null,
    colunas: [
      { origem: "codsit", cast: "int", pk: true },
      { origem: "dessit", cast: "text" },
      { origem: "desabr", cast: "text" },
      { origem: "tipsit", cast: "int" },
      { origem: "incabs", cast: "int" },
      { origem: "conabs", cast: "int" },
      { origem: "sitcmp", cast: "int" },
    ],
  },
  {
    jobName: "hcm-causas-demissao-sync",
    displayName: "Causas de Demissão (HCM)",
    tabela: "r042cau",
    tabelaLocal: "hcm_causas_demissao",
    campoData: null,
    colunas: [
      { origem: "caudem", cast: "int", pk: true },
      { origem: "desdem", cast: "text" },
    ],
  },
  {
    jobName: "hcm-motivos-alteracao-sync",
    displayName: "Motivos de Alteração (HCM)",
    tabela: "r076mot",
    tabelaLocal: "hcm_motivos_alteracao",
    campoData: null,
    colunas: [
      { origem: "codmot", cast: "int", pk: true },
      { origem: "nommot", cast: "text" },
      { origem: "tipmot", cast: "text" },
      { origem: "mtvalt", cast: "int" },
      { origem: "tpomvt", cast: "int" },
    ],
  },
  {
    jobName: "hcm-eventos-sync",
    displayName: "Eventos da Folha (HCM)",
    tabela: "r008evc",
    tabelaLocal: "hcm_eventos",
    campoData: null,
    colunas: [
      { origem: "codtab", cast: "int", pk: true },
      { origem: "codeve", cast: "int", pk: true },
      { origem: "deseve", cast: "text" },
      { origem: "tipeve", cast: "int" },
      { origem: "codcrt", cast: "int" },
      { origem: "nateve", cast: "int" },
      { origem: "rgreve", cast: "int" },
    ],
  },
  {
    jobName: "hcm-escalas-sync",
    displayName: "Escalas (HCM)",
    tabela: "r006esc",
    tabelaLocal: "hcm_escalas",
    campoData: null,
    colunas: [
      { origem: "codesc", cast: "int", pk: true },
      { origem: "nomesc", cast: "text" },
      { origem: "tabest", cast: "int" },
      { origem: "claesc", cast: "int" },
      { origem: "hordsr", cast: "bigint" },
      { origem: "horsem", cast: "bigint" },
      { origem: "hormes", cast: "bigint" },
      { origem: "tipesc", cast: "text" },
      { origem: "tipjor", cast: "int" },
      { origem: "desjor", cast: "text" },
      { origem: "turesc", cast: "int" },
      { origem: "escnot", cast: "text" },
    ],
  },
  {
    jobName: "hcm-horarios-sync",
    displayName: "Horários (HCM)",
    tabela: "r004hor",
    tabelaLocal: "hcm_horarios",
    campoData: null,
    colunas: [
      { origem: "codhor", cast: "int", pk: true },
      { origem: "deshor", cast: "text" },
      { origem: "tabest", cast: "int" },
      { origem: "turhor", cast: "int" },
      { origem: "jorhor", cast: "text" },
      { origem: "hortrb", cast: "int" },
      { origem: "horext", cast: "int" },
      { origem: "hornot", cast: "int" },
      { origem: "tiphor", cast: "int" },
    ],
  },
  {
    jobName: "hcm-colaboradores-sync",
    displayName: "Colaboradores (HCM)",
    tabela: "r034fun",
    tabelaLocal: "hcm_colaboradores",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "nomfun", cast: "text" },
      { origem: "apefun", cast: "text" },
      { origem: "datadm", cast: "date" },
      { origem: "tipadm", cast: "int" },
      { origem: "sitafa", cast: "int" },
      { origem: "estpos", cast: "int" },
      { origem: "postra", cast: "text" },
      { origem: "estcar", cast: "int" },
      { origem: "codcar", cast: "text" },
      { origem: "codesc", cast: "int" },
      { origem: "codtma", cast: "int" },
      { origem: "turint", cast: "int" },
      { origem: "codfil", cast: "int" },
      { origem: "taborg", cast: "int" },
      { origem: "numloc", cast: "int" },
      { origem: "codccu", cast: "text" },
      { origem: "tipcon", cast: "int" },
      { origem: "tipsex", cast: "text" },
      { origem: "estciv", cast: "int" },
      { origem: "grains", cast: "int" },
      { origem: "datnas", cast: "date" },
      { origem: "codnac", cast: "int" },
      { origem: "datafa", cast: "date" },
      { origem: "caudem", cast: "int" },
      { origem: "codmot", cast: "int" },
      { origem: "valsal", cast: "numeric" },
      { origem: "tipsal", cast: "int" },
      { origem: "datsal", cast: "date" },
      { origem: "horbas", cast: "int" },
      { origem: "horsem", cast: "bigint" },
      { origem: "hordsr", cast: "bigint" },
      { origem: "horsab", cast: "int" },
      { origem: "ultcal", cast: "int" },
    ],
  },
  {
    jobName: "hcm-afastamentos-sync",
    displayName: "Afastamentos (HCM)",
    tabela: "r038afa",
    tabelaLocal: "hcm_afastamentos",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datafa", cast: "date", pk: true },
      { origem: "horafa", cast: "int", pk: true },
      { origem: "datter", cast: "date" },
      { origem: "horter", cast: "int" },
      { origem: "prvter", cast: "date" },
      { origem: "sitafa", cast: "int" },
      { origem: "caudem", cast: "int" },
      { origem: "diajus", cast: "int" },
      { origem: "qhrafa", cast: "int" },
      { origem: "oriafa", cast: "int" },
    ],
  },
  {
    jobName: "hcm-historico-salarial-sync",
    displayName: "Histórico Salarial (HCM)",
    tabela: "r038hsa",
    tabelaLocal: "hcm_historico_salarial",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datalt", cast: "date", pk: true },
      { origem: "seqalt", cast: "int", pk: true },
      { origem: "codmot", cast: "int" },
      { origem: "valsal", cast: "numeric" },
      { origem: "tipsal", cast: "int" },
      { origem: "perdes", cast: "numeric" },
      { origem: "perrea", cast: "numeric" },
    ],
  },
  {
    jobName: "hcm-historico-local-sync",
    displayName: "Histórico de Local (HCM)",
    tabela: "r038hlo",
    tabelaLocal: "hcm_historico_local",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datalt", cast: "date", pk: true },
      { origem: "taborg", cast: "int" },
      { origem: "numloc", cast: "int" },
    ],
  },
  {
    jobName: "hcm-historico-cargo-sync",
    displayName: "Histórico de Cargo (HCM)",
    tabela: "r038hca",
    tabelaLocal: "hcm_historico_cargo",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datalt", cast: "date", pk: true },
      { origem: "estcar", cast: "int" },
      { origem: "codcar", cast: "text" },
      { origem: "codmot", cast: "int" },
    ],
  },
  {
    jobName: "hcm-calculos-folha-sync",
    displayName: "Cálculos de Folha (HCM)",
    tabela: "r044cal",
    tabelaLocal: "hcm_calculos_folha",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "codcal", cast: "int", pk: true },
      { origem: "tipcal", cast: "int" },
      { origem: "sitcal", cast: "text" },
      { origem: "perref", cast: "date" },
      { origem: "datpag", cast: "date" },
      { origem: "inicmp", cast: "date" },
      { origem: "fimcmp", cast: "date" },
      { origem: "grucal", cast: "int" },
    ],
  },
  {
    jobName: "hcm-verbas-folha-sync",
    displayName: "Verbas da Folha (HCM)",
    tabela: "r046ver",
    tabelaLocal: "hcm_verbas_folha",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "codcal", cast: "int", pk: true },
      { origem: "tabeve", cast: "int", pk: true },
      { origem: "codeve", cast: "int", pk: true },
      { origem: "refeve", cast: "numeric" },
      { origem: "valeve", cast: "numeric" },
      { origem: "orieve", cast: "text" },
    ],
  },
  {
    jobName: "hcm-rescisoes-sync",
    displayName: "Rescisões (HCM)",
    tabela: "r042rcm",
    tabelaLocal: "hcm_rescisoes",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datdem", cast: "date" },
      { origem: "caudem", cast: "int" },
      { origem: "datavi", cast: "date" },
      { origem: "datpag", cast: "date" },
      { origem: "fimctt", cast: "date" },
      { origem: "salfav", cast: "numeric" },
      { origem: "sldfgt", cast: "numeric" },
      { origem: "totpro", cast: "numeric" },
      { origem: "totdes", cast: "numeric" },
      { origem: "basfgt", cast: "numeric" },
    ],
  },
  {
    jobName: "hcm-verbas-rescisao-sync",
    displayName: "Verbas de Rescisão (HCM)",
    tabela: "r042rcv",
    tabelaLocal: "hcm_verbas_rescisao",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datpag", cast: "date", pk: true },
      { origem: "tclrcs", cast: "int", pk: true },
      { origem: "tabeve", cast: "int", pk: true },
      { origem: "codeve", cast: "int", pk: true },
      { origem: "refeve", cast: "numeric" },
      { origem: "valeve", cast: "numeric" },
    ],
  },
  {
    jobName: "hcm-apuracao-ponto-sync",
    displayName: "Apuração de Ponto (HCM)",
    tabela: "r066apu",
    tabelaLocal: "hcm_apuracao_ponto",
    campoData: "datapu",
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datapu", cast: "date", pk: true },
      { origem: "hordat", cast: "int" },
      { origem: "codesc", cast: "int" },
      { origem: "codtma", cast: "int" },
      { origem: "turint", cast: "int" },
      { origem: "perref", cast: "date" },
    ],
  },
  {
    jobName: "hcm-situacao-ponto-sync",
    displayName: "Situações do Ponto: apuradas (HCM)",
    tabela: "r066sit",
    tabelaLocal: "hcm_situacao_ponto",
    campoData: "datapu",
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "datapu", cast: "date", pk: true },
      { origem: "codsit", cast: "int", pk: true },
      { origem: "codrat", cast: "int", pk: true },
      { origem: "qtdhor", cast: "bigint" },
      { origem: "qtdhnc", cast: "bigint" },
      { origem: "perref", cast: "date" },
    ],
  },
  {
    jobName: "hcm-marcacoes-sync",
    displayName: "Marcações de Ponto (HCM)",
    tabela: "r070acc",
    tabelaLocal: "hcm_marcacoes",
    campoData: "datacc",
    colunas: [
      { origem: "numcra", cast: "bigint", pk: true },
      { origem: "datacc", cast: "date", pk: true },
      { origem: "horacc", cast: "int", pk: true },
      { origem: "seqacc", cast: "int", pk: true },
      { origem: "tipacc", cast: "int" },
      { origem: "diracc", cast: "text" },
      { origem: "numemp", cast: "int" },
      { origem: "tipcol", cast: "int" },
      { origem: "numcad", cast: "int" },
      { origem: "datapu", cast: "date" },
      { origem: "oriacc", cast: "text" },
      { origem: "usomar", cast: "int" },
    ],
  },
  {
    jobName: "hcm-lancamentos-bh-sync",
    displayName: "Lançamentos do Banco de Horas (HCM)",
    tabela: "r011lan",
    tabelaLocal: "hcm_lancamentos_bh",
    campoData: "datlan",
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "codbhr", cast: "int", pk: true },
      { origem: "datlan", cast: "date", pk: true },
      { origem: "codsit", cast: "int", pk: true },
      { origem: "orilan", cast: "text", pk: true },
      { origem: "sinlan", cast: "text" },
      { origem: "qtdhor", cast: "bigint" },
      { origem: "qtdpag", cast: "bigint" },
      { origem: "datcmp", cast: "date" },
      { origem: "perref", cast: "date" },
    ],
  },
  {
    jobName: "hcm-periodos-ferias-sync",
    displayName: "Períodos Aquisitivos de Férias (HCM)",
    tabela: "r040per",
    tabelaLocal: "hcm_periodos_ferias",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "iniper", cast: "date", pk: true },
      { origem: "fimper", cast: "date" },
      { origem: "qtddir", cast: "numeric" },
      { origem: "qtdfal", cast: "numeric" },
      { origem: "qtdafa", cast: "numeric" },
      { origem: "qtdsld", cast: "numeric" },
      { origem: "qtdabo", cast: "numeric" },
      { origem: "sitper", cast: "int" },
      { origem: "limcon", cast: "date" },
      { origem: "diadev", cast: "int" },
    ],
  },
  {
    jobName: "hcm-programacao-ferias-sync",
    displayName: "Programação de Férias (HCM)",
    tabela: "r040fem",
    tabelaLocal: "hcm_programacao_ferias",
    campoData: null,
    colunas: [
      { origem: "numemp", cast: "int", pk: true },
      { origem: "tipcol", cast: "int", pk: true },
      { origem: "numcad", cast: "int", pk: true },
      { origem: "iniper", cast: "date", pk: true },
      { origem: "inifer", cast: "date", pk: true },
      { origem: "tipfer", cast: "text" },
      { origem: "diafer", cast: "numeric" },
      { origem: "diaabo", cast: "numeric" },
      { origem: "datpag", cast: "date" },
      { origem: "fimfer", cast: "date" },
      { origem: "opc13s", cast: "text" },
    ],
  },
];
